
version: 2

sources:
  - name: Infofiscus
    database: DBT_INFOFISCUS_LANDING_DEV
    schema: SALESFORCE   
    tables: 
      - name: ACCOUNTS
      - name: CAMPAIGNS
      - name: CONTACTS 
      - name: CAMPAIGNMEMBER
      - name: LEADS
      - name: OPPORTUNITIES
