{{
    config(
        materialized = 'incremental',
        unique_key='ID',
        incremental_strategy='merge',
        merge_update_columns = ["ID","ISDELETED","MASTERRECORDID","NAME","TYPE",NULL AS "RECORDTYPEID","PARENTID","BILLINGSTREET",
        "BILLINGCITY","BILLINGSTATE","BILLINGPOSTALCODE","BILLINGCOUNTRY", NULL AS "BILLINGSTATECODE",
        NULL AS "BILLINGCOUNTRYCODE","BILLINGLATITUDE","BILLINGLONGITUDE","BILLINGGEOCODEACCURACY",
        "SHIPPINGSTREET","SHIPPINGCITY","SHIPPINGSTATE","SHIPPINGPOSTALCODE","SHIPPINGCOUNTRY",
        NULL AS "SHIPPINGSTATECODE", NULL AS "SHIPPINGCOUNTRYCODE","SHIPPINGLATITUDE","SHIPPINGLONGITUDE",
        "SHIPPINGGEOCODEACCURACY","PHONE","FAX","WEBSITE","PHOTOURL","SIC","INDUSTRY","ANNUALREVENUE",
        "NUMBEROFEMPLOYEES","OWNERSHIP","TICKERSYMBOL","DESCRIPTION","SITE","OWNERID","CREATEDDATE","CREATEDBYID",
        "LASTMODIFIEDDATE","LASTMODIFIEDBYID","SYSTEMMODSTAMP","LASTACTIVITYDATE","LASTVIEWEDDATE",
        "LASTREFERENCEDDATE",NULL AS "ISPARTNER",NULL AS "ISCUSTOMERPORTAL","JIGSAW","JIGSAWCOMPANYID",
        "ACCOUNTSOURCE","SICDESC","DANDBCOMPANYID","OPERATINGHOURSID", "DW_UPDATE_DT"],
        database="INFOFISCUS_DATAMART_DEV",
        post_hook="Update INFOFISCUS_LANDING_QA.PUBLIC.INFOFISCUS_CT CT SET LAST_RUN_DATE = CURRENT_TIMESTAMP() WHERE
SRC_VIEW = 'VW_<SRC_TABLE>' AND TGT_TABLE = '<TGT_TABLE>' AND ENVIRONMENT = 'DATA_MART';"
    )
}}

SELECT 
"ID","ISDELETED","MASTERRECORDID","NAME","TYPE",NULL AS "RECORDTYPEID","PARENTID","BILLINGSTREET",
        "BILLINGCITY","BILLINGSTATE","BILLINGPOSTALCODE","BILLINGCOUNTRY", NULL AS "BILLINGSTATECODE",
        NULL AS "BILLINGCOUNTRYCODE","BILLINGLATITUDE","BILLINGLONGITUDE","BILLINGGEOCODEACCURACY",
        "SHIPPINGSTREET","SHIPPINGCITY","SHIPPINGSTATE","SHIPPINGPOSTALCODE","SHIPPINGCOUNTRY",
        NULL AS "SHIPPINGSTATECODE", NULL AS "SHIPPINGCOUNTRYCODE","SHIPPINGLATITUDE","SHIPPINGLONGITUDE",
        "SHIPPINGGEOCODEACCURACY","PHONE","FAX","WEBSITE","PHOTOURL","SIC","INDUSTRY","ANNUALREVENUE",
        "NUMBEROFEMPLOYEES","OWNERSHIP","TICKERSYMBOL","DESCRIPTION","SITE","OWNERID","CREATEDDATE","CREATEDBYID",
        "LASTMODIFIEDDATE","LASTMODIFIEDBYID","SYSTEMMODSTAMP","LASTACTIVITYDATE","LASTVIEWEDDATE",
        "LASTREFERENCEDDATE",NULL AS "ISPARTNER",NULL AS "ISCUSTOMERPORTAL","JIGSAW","JIGSAWCOMPANYID",
        "ACCOUNTSOURCE","SICDESC","DANDBCOMPANYID","OPERATINGHOURSID", "ID" AS "DW_KEY_ID",     
CURRENT_TIMESTAMP AS "DW_INSERT_DT", CURRENT_TIMESTAMP AS "DW_UPDATE_DT" 
FROM {{ref('STG_ACCOUNTS')}}
            