{{
    config(
        materialized = 'incremental',
        unique_key='ID',
        incremental_strategy='merge',
        merge_update_columns = ["ID","ISDELETED","NAME","PARENTID","RECORDTYPEID","TYPE","STATUS","STARTDATE","ENDDATE",
                                "EXPECTEDREVENUE","BUDGETEDCOST","ACTUALCOST","CAMPAIGNIMAGEID","EXPECTEDRESPONSE","NUMBERSENT",
                                "ISACTIVE","DESCRIPTION","NUMBEROFLEADS","NUMBEROFCONVERTEDLEADS","NUMBEROFCONTACTS","NUMBEROFRESPONSES",
                                "NUMBEROFOPPORTUNITIES","NUMBEROFWONOPPORTUNITIES","AMOUNTALLOPPORTUNITIES","AMOUNTWONOPPORTUNITIES",
                                "CURRENCYISOCODE","OWNERID", "TENANTID","CREATEDDATE","CREATEDBYID","LASTMODIFIEDDATE",
                                "LASTMODIFIEDBYID","SYSTEMMODSTAMP","LASTACTIVITYDATE","LASTVIEWEDDATE","LASTREFERENCEDDATE",
                                "CAMPAIGNMEMBERRECORDTYPEID", "DW_UPDATE_DT"
                                ],
        database="INFOFISCUS_DATAMART_DEV",
        post_hook="Update INFOFISCUS_LANDING_QA.PUBLIC.INFOFISCUS_CT CT SET LAST_RUN_DATE = CURRENT_TIMESTAMP() WHERE
SRC_VIEW = 'VW_<SRC_TABLE>' AND TGT_TABLE = '<TGT_TABLE>' AND ENVIRONMENT = 'DATA_MART';"
    )
}}

SELECT 
"ID","ISDELETED","NAME","PARENTID",NULL AS "RECORDTYPEID","TYPE","STATUS","STARTDATE","ENDDATE",
"EXPECTEDREVENUE","BUDGETEDCOST","ACTUALCOST",NULL AS "CAMPAIGNIMAGEID","EXPECTEDRESPONSE","NUMBERSENT",
"ISACTIVE","DESCRIPTION","NUMBEROFLEADS","NUMBEROFCONVERTEDLEADS","NUMBEROFCONTACTS","NUMBEROFRESPONSES",
"NUMBEROFOPPORTUNITIES","NUMBEROFWONOPPORTUNITIES","AMOUNTALLOPPORTUNITIES","AMOUNTWONOPPORTUNITIES",
NULL AS "CURRENCYISOCODE","OWNERID", NULL AS "TENANTID","CREATEDDATE","CREATEDBYID","LASTMODIFIEDDATE",
"LASTMODIFIEDBYID","SYSTEMMODSTAMP","LASTACTIVITYDATE","LASTVIEWEDDATE","LASTREFERENCEDDATE",
"CAMPAIGNMEMBERRECORDTYPEID", "ID" AS "DW_KEY_ID",     
CURRENT_TIMESTAMP AS "DW_INSERT_DT", CURRENT_TIMESTAMP AS "DW_UPDATE_DT" 
FROM {{ref('STG_CAMPAIGNS')}}
            